config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: {format: :json} do
    resources :users, only: [:create, :update]
    resource :session, only: [:create, :destroy, :show]
    resources :articles, only: [:index, :show, :create, :update, :destroy]
    resources :outfits, only: [:index, :create]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  TEMP_OFFSETS = [-5, 0, 5]

  validates :email, :name, :temp_offset, :zipcode, :session_token, :password_digest, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :temp_offset, inclusion: TEMP_OFFSETS
  validates :zipcode, zipcode: { country_code: :us }

  has_many :articles, dependent: :destroy
  has_many :outfits, dependent: :destroy

  after_initialize :ensure_session_token

  ARTICLE_TYPES = {
    "top" => :tops,
    "bottom" => :bottoms,
    "outerwear" => :outerwear,
    "dress" => :dresses,
    "shoes" => :shoes,
    "misc" => :misc
  }

  def articles_by_type
    group = Hash.new
    ARTICLE_TYPES.each do |_, type|
      group[type] = {ids: []}
    end
    self.articles.each do |article|
      group[ARTICLE_TYPES[article.article_type]][article.id] = article
      group[ARTICLE_TYPES[article.article_type]][:ids] << article.id
    end
    group
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return user if user && user.is_password?(password)
    nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.save
      log_in!(@user)
      render :show
    else
      render json: @user.errors.full_messages, status: 422
  end

  def update
    @user = current_user
    if @user.update!(user_params)
      render :show
    else
      render json: @user.errors.full_messages, status: 422
    end
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:password,:temp_offset,:zipcode)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    if current_user
      redirect_to root_url
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    @user.temp_offset = @user.temp_offset.to_i
    if @user.save
      log_in!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:temp_offset,:zipcode)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<span class="logo">StyleList</span>
<div class="signup">
  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <p><%= error %></p>
    <% end %>
  <% end %>
  <form class="signup-form" action="<%= users_url %>" method="post">
    <%= auth_token_input %>
    <div class="signup-labels">
      <p class="signup-title">Create Account</p>
      <input class="signup-input" type="text" name="user[name]" placeholder="Name" value="<%= @user.name %>">
      <input class="signup-input" type="text" name="user[email]" placeholder="Email"value="<%= @user.email %>">
      <input class="signup-input" type="password" placeholder="Password" name="user[password]" value="">
      <input class="signup-input" type="text" name="user[zipcode]" placeholder="Zipcode" value="<%= @user.zipcode %>">
      <label class="signup-label">
        <%= radio_button("user", "temp_offset", -5) %>
        Do you get cold too easily...
        <br>
        <%= radio_button("user", "temp_offset", 0) %>
        Usually happy as a clam...
        <br>
        <%= radio_button("user", "temp_offset", 5) %>
        Or find yourself too warm?
      </label>
      <input class="signup-submit" type="submit" value="Sign Up">
    </div>

    <%= link_to "I already have an account", new_session_url, class: "signin-link" %>

  </form>
</div>